// Generated by CoffeeScript 1.7.1
var Person, me, objArr, objName, strName;

strName = "hi";

objName = {
  age: 10,
  lo: "korea"
};

objArr = [1, 2, 3, 4, 5];

Person = (function() {
  function Person(options) {
    this.name = options.name, this.age = options.age, this.sex = options.sex;
  }

  Person.prototype.setName = function(strName) {
    return this.name = strName;
  };

  Person.prototype.getName = function() {
    return this.name;
  };

  Person.prototype.logName = function(logName) {
    this.setName(logName);
    return console.log(this.getName());
  };

  return Person;

})();

me = new Person({
  name: "gi",
  age: 39,
  sex: "mail"
});

me.logName("change your name");
